site_name: Benjamin Ambrose

docs_dir: src
draft_docs: vault
site_dir: docs

theme:
  name: landing

  avatar: assets/avatar.png
  background: |
    linear-gradient(
        45deg, 
        color-mix(in srgb, var(--crust) 100%, transparent), 
        color-mix(in srgb, var(--base) 80%, transparent)
    ), fixed center/cover url(assets/starmap.png)

  tagline: |
    he/him /[bɛnʤʌmɪn æmbrəʊz](http://ipa-reader.xyz/?text=bɛnʤʌmɪn%20æmbrəʊz)/
  footer: |
      Compiled from markdown using [MkDocs](https://www.mkdocs.org/), hosted via [GitHub Pages](https://pages.github.com/). Theme by [Todd Parsons](https://toddparsons.co.uk).
  page_source: 
    link: https://benjaminambrose.github.io/benambrose/
    icon: github
  socials:
    - label: Email
      link: mailto:b.ambrose@lms.mrc.ac.uk
      icon: at
    - label: GitHub
      link: https://github.com/BenjaminAmbrose
      icon: [brands, github]
    - label: Google Scholar
      link: https://scholar.google.com/citations?user=q_Xfc3sAAAAJ&hl=en
      icon: [brands, google-scholar]
  
  # style options
  header_layout:
    - avatar
    - socials
    - title
    - tagline    
  content_box_opacity: 0
  avatar_size: 8rem
  round_avatar: True
  
  # theme colours
  colors:
    # colours
    primary: "#dd7878"
    secondary: "#7287fd"
    tertiary: "#dd7878"
    # shades
    base: "#24273a"
    mantle: "#1e2030"
    crust: "#181926"
    overlay: "#9B9B9E"
    # text
    text: "#c6d0f5"
    hltext: "#24273a"
  
  # dark mode colors
  colors_dark:
    # colours
    primary: "#dd7878"
    secondary: "#7287fd"
    tertiary: "#dd7878"
    # shades
    base: "#24273a"
    mantle: "#1e2030"
    crust: "#181926"
    overlay: "#9B9B9E"
    # text
    text: "#c6d0f5"
    hltext: "#24273a"
  
  # fonts
  fonts:
    body: Maven Pro
    heading: Oswald

hooks:
  - hooks/md_filter.py
  - hooks/layout.py

markdown_extensions:
  - toc
  - attr_list
  - def_list
  - md_in_html
  - nl2br
